name: vasu - Scheduled Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  push:
    paths:
      - '.github/workflows/vasu-scheduled-workflow.yml'
      
      jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Display current date and time
        run: echo "The current date and time is $(date)"
